
export interface Category {
  id: string;
  name: string;
  items: string[];
}

export interface PuzzleData {
  title: string;
  story: string;
  categories: Category[]; // Should be exactly 3 categories for this UI layout
  clues: string[];
  solution: Record<string, string[]>; // Maps item -> associated items (e.g. "Alice": ["Red", "London"])
}

export enum CellState {
  EMPTY = 0,
  FALSE = 1,      // Manual 'X'
  TRUE = 2,       // 'O' (Green marble) - User input
  FALSE_AUTO = 3, // Auto 'X' (Generated by logic)
  
  // Game Over Comparison States
  TRUE_CORRECT = 4,   // User input matched solution
  TRUE_INCORRECT = 5, // User input did NOT match solution
  MISSED = 6          // Solution required this, but User left it empty/false
}

// Key format: "catIndex:itemIndex|catIndex:itemIndex" (sorted to be unique)
export type GridState = Record<string, CellState>;

export interface PuzzleConfig {
  theme?: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}